spring:
  application:
    name: Fleet Management
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  jackson:
    mapper:
      accept-case-insensitive-enums: true
management:
    endpoints:
      web:
        exposure:
          include: "*"
springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
